"""
Tests the pre-fabricated plans generated by the prefab_plan_generator.py script
and listed on the Pylinac docs site for use by the public.
"""

import os
import re
import unittest
from pathlib import Path
from unittest import TestCase

import pydicom

from tests_basic.utils import cloud_test_downloader, requires_cloud_data


class TestGeneratedPlans(TestCase):
    @classmethod
    @requires_cloud_data(
        folders={"cloud_folder": ["rtplans"]},
        folder_repos={"cloud_folder": "pylinac_demo_files"},
    )
    def _set_cloud_folder(cls, cloud_folder: str) -> None:
        cls.cloud_folder = Path(cloud_folder)

    @classmethod
    def setUpClass(cls) -> None:
        # if we're in CI/CD, download from the GCP bucket
        if os.environ.get("CI"):
            cls._set_cloud_folder()
        # if we're local, use the locally generated plans
        else:
            local_folder = Path(__file__).parent.parent / "scripts"
            if len(list(local_folder.glob("R2*"))) > 0:
                cls.cloud_folder = local_folder
            elif cloud_test_downloader.is_authenticated:
                cls._set_cloud_folder()
            else:
                raise unittest.SkipTest(
                    "No local generated plans found and cloud test data is unavailable."
                )

    def test_num_rev2_plans(self):
        self.assertEqual(len(list(Path(self.cloud_folder).glob("R2*"))), 12)

    def test_all_energies_of_plan_are_the_same(self):
        for plan in Path(self.cloud_folder).glob("R2*"):
            energy_str = plan.name.split("_")[1]
            energy = int(re.match(r"(\d+)(MV|MVFFF)?", energy_str).group(1))
            ds = pydicom.dcmread(plan)
            for beam in ds.BeamSequence:
                self.assertEqual(
                    int(beam.ControlPointSequence[0].NominalBeamEnergy),
                    energy,
                    msg=f"Plan {plan} has a beam {beam.BeamName} with a different energy than the plan",
                )

    def test_fluence_mode_of_plan_are_the_same(self):
        FLUENCE_MAP = {"NON_STANDARD": True, "STANDARD": False}
        for plan in Path(self.cloud_folder).glob("R2*"):
            is_fff_beam = "FFF" in plan.name
            ds = pydicom.dcmread(plan)
            for beam in ds.BeamSequence:
                fluence = beam.PrimaryFluenceModeSequence[0].FluenceMode
                self.assertEqual(
                    FLUENCE_MAP[fluence],
                    is_fff_beam,
                    msg=f"Plan {plan} has a beam {beam.BeamName} with a different MLC than the plan",
                )

    def test_nominal_dose_rate_is_the_same_per_plan(self):
        for plan in Path(self.cloud_folder).glob("R2*"):
            ds = pydicom.dcmread(plan)
            first_dose_rate = int(
                ds.BeamSequence[0].ControlPointSequence[0].DoseRateSet
            )
            for beam in ds.BeamSequence[1:]:
                self.assertEqual(
                    int(beam.ControlPointSequence[0].DoseRateSet),
                    first_dose_rate,
                    msg=f"Plan {plan} has a beam {beam.BeamName} with a different dose rate than the plan",
                )
