# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing
import os
import pathlib

class XIMHeader:
    identifier: builtins.str
    version: builtins.int
    width: builtins.int
    height: builtins.int
    bits_per_pixel: builtins.int
    bytes_per_pixel: builtins.int
    is_compressed: builtins.bool

class XIMHistogram:
    histogram: builtins.list[builtins.int]

class XIMImage:
    header: XIMHeader
    numpy: numpy.typing.NDArray[numpy.int8] | numpy.typing.NDArray[numpy.int16] | numpy.typing.NDArray[numpy.int32] | numpy.typing.NDArray[numpy.int64]
    histogram: builtins.list[builtins.int]
    properties: builtins.dict[builtins.str, builtins.int | builtins.float | builtins.str | builtins.list[builtins.float] | builtins.list[builtins.int]]
    def __new__(cls,image_path:builtins.str | os.PathLike | pathlib.Path): ...

class XIMProperties:
    ...

