# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\James\Dropbox\Programming\Python\Projects\PyCharm Projects\pylinac\pyqa_gui\PyQAui.ui'
#
# Created: Thu Oct 23 15:30:40 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PyQA_MainWindow(object):
    def setupUi(self, PyQA_MainWindow):
        PyQA_MainWindow.setObjectName("PyQA_MainWindow")
        PyQA_MainWindow.resize(849, 664)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyQA_MainWindow.sizePolicy().hasHeightForWidth())
        PyQA_MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(PyQA_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 590, 191, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Title_label = QtGui.QLabel(self.centralwidget)
        self.Title_label.setGeometry(QtCore.QRect(320, 10, 141, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title_label.sizePolicy().hasHeightForWidth())
        self.Title_label.setSizePolicy(sizePolicy)
        self.Title_label.setScaledContents(True)
        self.Title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.main_widget = QtGui.QTabWidget(self.centralwidget)
        self.main_widget.setEnabled(True)
        self.main_widget.setGeometry(QtCore.QRect(20, 60, 811, 521))
        self.main_widget.setTabPosition(QtGui.QTabWidget.North)
        self.main_widget.setTabShape(QtGui.QTabWidget.Rounded)
        self.main_widget.setElideMode(QtCore.Qt.ElideNone)
        self.main_widget.setObjectName("main_widget")
        self.load_data_tab = QtGui.QWidget()
        self.load_data_tab.setObjectName("load_data_tab")
        self.stargroupbox = QtGui.QGroupBox(self.load_data_tab)
        self.stargroupbox.setGeometry(QtCore.QRect(20, 30, 371, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setBold(False)
        self.stargroupbox.setFont(font)
        self.stargroupbox.setAlignment(QtCore.Qt.AlignCenter)
        self.stargroupbox.setFlat(False)
        self.stargroupbox.setCheckable(False)
        self.stargroupbox.setObjectName("stargroupbox")
        self.star_load_img = QtGui.QPushButton(self.stargroupbox)
        self.star_load_img.setGeometry(QtCore.QRect(120, 100, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.star_load_img.sizePolicy().hasHeightForWidth())
        self.star_load_img.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.star_load_img.setFont(font)
        self.star_load_img.setDefault(False)
        self.star_load_img.setObjectName("star_load_img")
        self.label_5 = QtGui.QLabel(self.stargroupbox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.autoloadStar = QtGui.QPushButton(self.stargroupbox)
        self.autoloadStar.setGeometry(QtCore.QRect(20, 110, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoloadStar.setFont(font)
        self.autoloadStar.setObjectName("autoloadStar")
        self.stargroupbox_2 = QtGui.QGroupBox(self.load_data_tab)
        self.stargroupbox_2.setGeometry(QtCore.QRect(420, 30, 371, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setBold(False)
        self.stargroupbox_2.setFont(font)
        self.stargroupbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stargroupbox_2.setFlat(False)
        self.stargroupbox_2.setCheckable(False)
        self.stargroupbox_2.setObjectName("stargroupbox_2")
        self.vmat_load_open_button = QtGui.QPushButton(self.stargroupbox_2)
        self.vmat_load_open_button.setGeometry(QtCore.QRect(30, 100, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmat_load_open_button.sizePolicy().hasHeightForWidth())
        self.vmat_load_open_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vmat_load_open_button.setFont(font)
        self.vmat_load_open_button.setDefault(False)
        self.vmat_load_open_button.setObjectName("vmat_load_open_button")
        self.label_6 = QtGui.QLabel(self.stargroupbox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.vmat_load_dmlc_button = QtGui.QPushButton(self.stargroupbox_2)
        self.vmat_load_dmlc_button.setGeometry(QtCore.QRect(200, 100, 141, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmat_load_dmlc_button.sizePolicy().hasHeightForWidth())
        self.vmat_load_dmlc_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vmat_load_dmlc_button.setFont(font)
        self.vmat_load_dmlc_button.setDefault(False)
        self.vmat_load_dmlc_button.setObjectName("vmat_load_dmlc_button")
        self.autoloadvmat_drgs = QtGui.QPushButton(self.load_data_tab)
        self.autoloadvmat_drgs.setGeometry(QtCore.QRect(700, 200, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoloadvmat_drgs.setFont(font)
        self.autoloadvmat_drgs.setObjectName("autoloadvmat_drgs")
        self.autoloadvmat_drmlc = QtGui.QPushButton(self.load_data_tab)
        self.autoloadvmat_drmlc.setGeometry(QtCore.QRect(700, 230, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoloadvmat_drmlc.setFont(font)
        self.autoloadvmat_drmlc.setObjectName("autoloadvmat_drmlc")
        self.main_widget.addTab(self.load_data_tab, "")
        self.view_data_tab = QtGui.QWidget()
        self.view_data_tab.setObjectName("view_data_tab")
        self.View_Data_mplw_left = MatplotlibWidget(self.view_data_tab)
        self.View_Data_mplw_left.setGeometry(QtCore.QRect(10, 10, 371, 401))
        self.View_Data_mplw_left.setCursor(QtCore.Qt.CrossCursor)
        self.View_Data_mplw_left.setAutoFillBackground(False)
        self.View_Data_mplw_left.setObjectName("View_Data_mplw_left")
        self.View_Data_mplw_right = MatplotlibWidget(self.view_data_tab)
        self.View_Data_mplw_right.setGeometry(QtCore.QRect(410, 10, 371, 401))
        self.View_Data_mplw_right.setCursor(QtCore.Qt.CrossCursor)
        self.View_Data_mplw_right.setAutoFillBackground(False)
        self.View_Data_mplw_right.setObjectName("View_Data_mplw_right")
        self.main_widget.addTab(self.view_data_tab, "")
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.Settings_tabWidget = QtGui.QTabWidget(self.settings_tab)
        self.Settings_tabWidget.setGeometry(QtCore.QRect(106, 80, 551, 361))
        self.Settings_tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Settings_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.Settings_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.Settings_tabWidget.setObjectName("Settings_tabWidget")
        self.star_settings_tab = QtGui.QWidget()
        self.star_settings_tab.setObjectName("star_settings_tab")
        self.star_img_inversion = QtGui.QCheckBox(self.star_settings_tab)
        self.star_img_inversion.setGeometry(QtCore.QRect(150, 260, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.star_img_inversion.setFont(font)
        self.star_img_inversion.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.star_img_inversion.setChecked(True)
        self.star_img_inversion.setObjectName("star_img_inversion")
        self.groupBox_4 = QtGui.QGroupBox(self.star_settings_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 10, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.star_radius = QtGui.QSpinBox(self.groupBox_4)
        self.star_radius.setGeometry(QtCore.QRect(210, 30, 51, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.star_radius.sizePolicy().hasHeightForWidth())
        self.star_radius.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.star_radius.setFont(font)
        self.star_radius.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.star_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.star_radius.setMinimum(5)
        self.star_radius.setMaximum(95)
        self.star_radius.setProperty("value", 50)
        self.star_radius.setObjectName("star_radius")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 59, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(30, 60, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_5 = QtGui.QGroupBox(self.star_settings_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(70, 130, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.star_min_height = QtGui.QSpinBox(self.groupBox_5)
        self.star_min_height.setGeometry(QtCore.QRect(250, 20, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.star_min_height.setFont(font)
        self.star_min_height.setStatusTip("")
        self.star_min_height.setWhatsThis("")
        self.star_min_height.setMinimum(10)
        self.star_min_height.setMaximum(90)
        self.star_min_height.setSingleStep(5)
        self.star_min_height.setProperty("value", 30)
        self.star_min_height.setObjectName("star_min_height")
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_11 = QtGui.QLabel(self.star_settings_tab)
        self.label_11.setGeometry(QtCore.QRect(60, 310, 431, 20))
        self.label_11.setObjectName("label_11")
        self.Settings_tabWidget.addTab(self.star_settings_tab, "")
        self.vmat_settings_tab = QtGui.QWidget()
        self.vmat_settings_tab.setObjectName("vmat_settings_tab")
        self.groupBox_2 = QtGui.QGroupBox(self.vmat_settings_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 20, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.vmat_test_box = QtGui.QComboBox(self.groupBox_2)
        self.vmat_test_box.setGeometry(QtCore.QRect(100, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vmat_test_box.setFont(font)
        self.vmat_test_box.setObjectName("vmat_test_box")
        self.vmat_test_box.addItem("")
        self.vmat_test_box.addItem("")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtGui.QGroupBox(self.vmat_settings_tab)
        self.groupBox_3.setGeometry(QtCore.QRect(100, 150, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.vmat_tolerance_box = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.vmat_tolerance_box.setGeometry(QtCore.QRect(190, 30, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vmat_tolerance_box.setFont(font)
        self.vmat_tolerance_box.setDecimals(1)
        self.vmat_tolerance_box.setMinimum(0.1)
        self.vmat_tolerance_box.setMaximum(10.0)
        self.vmat_tolerance_box.setSingleStep(0.5)
        self.vmat_tolerance_box.setProperty("value", 3.0)
        self.vmat_tolerance_box.setObjectName("vmat_tolerance_box")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(70, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.vmat_settings_tab)
        self.label_10.setGeometry(QtCore.QRect(60, 310, 431, 20))
        self.label_10.setObjectName("label_10")
        self.Settings_tabWidget.addTab(self.vmat_settings_tab, "")
        self.analyze_button = QtGui.QPushButton(self.settings_tab)
        self.analyze_button.setGeometry(QtCore.QRect(320, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.analyze_button.setFont(font)
        self.analyze_button.setObjectName("analyze_button")
        self.main_widget.addTab(self.settings_tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.qual_mplw_left = MatplotlibWidget(self.tab_4)
        self.qual_mplw_left.setGeometry(QtCore.QRect(10, 70, 351, 351))
        self.qual_mplw_left.setCursor(QtCore.Qt.CrossCursor)
        self.qual_mplw_left.setAutoFillBackground(False)
        self.qual_mplw_left.setObjectName("qual_mplw_left")
        self.qual_mplw_right = MatplotlibWidget(self.tab_4)
        self.qual_mplw_right.setGeometry(QtCore.QRect(380, 70, 351, 351))
        self.qual_mplw_right.setCursor(QtCore.Qt.CrossCursor)
        self.qual_mplw_right.setAutoFillBackground(False)
        self.qual_mplw_right.setObjectName("qual_mplw_right")
        self.qual_mplw_main = MatplotlibWidget(self.tab_4)
        self.qual_mplw_main.setGeometry(QtCore.QRect(210, 20, 421, 461))
        self.qual_mplw_main.setCursor(QtCore.Qt.CrossCursor)
        self.qual_mplw_main.setAutoFillBackground(False)
        self.qual_mplw_main.setObjectName("qual_mplw_main")
        self.main_widget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 311, 401))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.results_browser = QtGui.QTextBrowser(self.groupBox)
        self.results_browser.setGeometry(QtCore.QRect(10, 20, 291, 371))
        self.results_browser.setObjectName("results_browser")
        self.quan_mplw = MatplotlibWidget(self.tab_5)
        self.quan_mplw.setGeometry(QtCore.QRect(380, 20, 401, 331))
        self.quan_mplw.setCursor(QtCore.Qt.CrossCursor)
        self.quan_mplw.setAutoFillBackground(False)
        self.quan_mplw.setObjectName("quan_mplw")
        self.main_widget.addTab(self.tab_5, "")
        PyQA_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PyQA_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PyQA_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PyQA_MainWindow)
        self.statusbar.setObjectName("statusbar")
        PyQA_MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(PyQA_MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PyQA_MainWindow)
        self.main_widget.setCurrentIndex(0)
        self.Settings_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PyQA_MainWindow)

    def retranslateUi(self, PyQA_MainWindow):
        PyQA_MainWindow.setWindowTitle(QtGui.QApplication.translate("PyQA_MainWindow", "PyQA", None, QtGui.QApplication.UnicodeUTF8))
        self.Title_label.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">PyQA</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.stargroupbox.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Starshot Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.star_load_img.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load Starshot Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Starshot images test the circular variation of mechanical parts of the linear accelerator. Typically, the gantry, collimator, and couch are tested. These are usually irradiated film or superimposed EPID images (for collimator or couch measurements).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.autoloadStar.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load Starshot", None, QtGui.QApplication.UnicodeUTF8))
        self.stargroupbox_2.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "VMAT QA Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.vmat_load_open_button.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load Open Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">Volumetric Modulated Arc Therapy machine QA is done by testing the gantry speed, variable dose rate, and MLC speeds simultaneously. The tests expected to be done and that are analyzed are those proposed by <a href=\"http://scitation.aip.org/content/aapm/journal/medphys/38/3/10.1118/1.3552922\"><span style=\" text-decoration: underline; color:#0000ff;\">Jorgensent et al.</span></a> Two tests are available: Dose Rate Gantry Speed and Dose Rate MLC Speed.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.vmat_load_dmlc_button.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load DMLC Field", None, QtGui.QApplication.UnicodeUTF8))
        self.autoloadvmat_drgs.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load DRGS", None, QtGui.QApplication.UnicodeUTF8))
        self.autoloadvmat_drmlc.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Load DRMLC", None, QtGui.QApplication.UnicodeUTF8))
        self.main_widget.setTabText(self.main_widget.indexOf(self.load_data_tab), QtGui.QApplication.translate("PyQA_MainWindow", "Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.main_widget.setTabText(self.main_widget.indexOf(self.view_data_tab), QtGui.QApplication.translate("PyQA_MainWindow", "Data View", None, QtGui.QApplication.UnicodeUTF8))
        self.star_img_inversion.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Allow automatic image inversion", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Radius %:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">Radius is the value between the automatically-determined starting point, which should be near the radiation isocenter, and the closest image edge.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Peak Height", None, QtGui.QApplication.UnicodeUTF8))
        self.star_min_height.setToolTip(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p>Minimum Peak Height changes how &quot;tall&quot; a star strip has to be before it\'s considered a true strip. </p><p>-Set this<span style=\" font-weight:600;\"> lower</span> for cases where the strips have much different pixel values. E.g. if the algorithm doesn\'t catch a strip peak this parameter may be too high. </p><p>-Set this <span style=\" font-weight:600;\">higher</span> for noisy images. E.g. the algorithm may catch a noisy region as a strip when it\'s not. If so, increase this parameter</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Minimum Peak Height %:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">Peak Height is the pixel value a radiation spoke must be higher than (relative to the maximum value) to be considered a valid peak. This prevents interference from noise. If radiation strips are different in magnitude (e.g. different MU), lower this value if need be.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">For more information about the Starshot algorithm and settings, visit the <a href=\"http://pylinac.readthedocs.org/en/latest/starshot_docs.html#algorithm\"><span style=\" text-decoration: underline; color:#0000ff;\">documentation.</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Settings_tabWidget.setTabText(self.Settings_tabWidget.indexOf(self.star_settings_tab), QtGui.QApplication.translate("PyQA_MainWindow", "Starshot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.vmat_test_box.setItemText(0, QtGui.QApplication.translate("PyQA_MainWindow", "Dose Rate Gantry Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.vmat_test_box.setItemText(1, QtGui.QApplication.translate("PyQA_MainWindow", "Dose Rate MLC Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">Select the test to be performed. DRGS is a 7-segment test, and DRMLC is a 4 segment test.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Deviation Tolerance %:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">Tolerance is the value that a sample must be below to be considered passing. The calculation follows that given by Jorgensen et al.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PyQA_MainWindow", "<html><head/><body><p align=\"center\">For more information about the VMAT QA algorithm and settings, visit the <a href=\"http://pylinac.readthedocs.org/en/latest/vmat_docs.html#algorithm\"><span style=\" text-decoration: underline; color:#0000ff;\">documentation.</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Settings_tabWidget.setTabText(self.Settings_tabWidget.indexOf(self.vmat_settings_tab), QtGui.QApplication.translate("PyQA_MainWindow", "VMAT", None, QtGui.QApplication.UnicodeUTF8))
        self.analyze_button.setText(QtGui.QApplication.translate("PyQA_MainWindow", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.main_widget.setTabText(self.main_widget.indexOf(self.settings_tab), QtGui.QApplication.translate("PyQA_MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.main_widget.setTabText(self.main_widget.indexOf(self.tab_4), QtGui.QApplication.translate("PyQA_MainWindow", "Qualitative Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.main_widget.setTabText(self.main_widget.indexOf(self.tab_5), QtGui.QApplication.translate("PyQA_MainWindow", "Quantitative Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("PyQA_MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PyQA_MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from pyqa_gui.matplotlibwidget import MatplotlibWidget
